// Detailed information for each spot from the PDF documentation
// This data includes descriptions, addresses, business hours, fees, and website URLs

export interface SpotDetails {
  id: number;
  description: string;
  address: string | null;
  phone: string | null;
  businessHours: string | null;
  website: string | null;
  fees: string | null;
  busCourses: string[];
}

export const spotDetails: Record<number, SpotDetails> = {
  1: {
    id: 1,
    description: "Located at the entrance to Nasu Highlands, Roadside Station Nasu Highlands Yuai no Mori has continued to develop as the center of Nasu's tourism and arts. It is a place where everyone can enjoy shopping, dining, and experiences. You can spend your time here while fully enjoying the nature of Nasu.",
    address: "593-8 Takaku-o, Nasu Town 325-0303",
    phone: null,
    businessHours: "Tourist Information Center: 9:00 AM - 5:00 PM, Nasutoran: 11:00 AM - 3:00 PM, Closed: Open year-round",
    website: "https://www.yuainomori.com/",
    fees: "Free",
    busCourses: ["A", "C", "D", "E", "F"],
  },
  2: {
    id: 2,
    description: "Nestled in the vast natural beauty of Nasu Highlands, this resort hotel offers a stay that heals both mind and body. Characterized by its spacious Western-style building, the generously sized guest rooms exude a calm atmosphere. Dining features wellness menus including buffets and course meals that highlight local ingredients.",
    address: "6437 Takaku-ko, Nasu Town 325-0001",
    phone: null,
    businessHours: "Check-in: 3:00 PM, Check-out: 11:00 AM, Hot Springs: 4:00 PM - 11:00 PM / 1:00 PM - 2:00 AM",
    website: "https://dormy-hotels.com/resort/hotels/nasu/",
    fees: "Starting at ¥15,000 per person per night (includes dinner and breakfast)",
    busCourses: ["A", "C", "D", "E", "F"],
  },
  3: {
    id: 3,
    description: "Spacious guest rooms are ideal for families, and the resort offers a wealth of activities and entertainment. Dining options include a buffet featuring a wide variety of Japanese and Western dishes, as well as authentic restaurants where you can savor the delicious flavors of local ingredients. This popular resort in Nasu offers comfortable stays for guests of all ages.",
    address: "1 Takaku-cho, Nasu-machi 325-0302",
    phone: null,
    businessHours: "Check-in: 12:30 PM, Check-out: 11:00 AM, Hot Springs: 12:00 PM - 10:00 PM",
    website: "https://www.epinard.jp/",
    fees: "From ¥13,300 per person per night (includes dinner and breakfast)",
    busCourses: ["A", "C", "D", "E", "F"],
  },
  4: {
    id: 4,
    description: "This popular amusement facility in Nasu Highlands offers a gemstone hunting experience. Its 'Underground Mine Course,' where you dip your hands in water to search for gems, is especially popular. It's an interactive spot where you can find colorful natural stones, and with a bit of luck, you might even discover rare stones.",
    address: "123 Takaku-cho, Nasu-machi 325-0302",
    phone: null,
    businessHours: "10:00 AM - 5:00 PM, Underground Mine: 10:00 AM - 4:30 PM, Regular Holidays: Wednesday, Thursday",
    website: "https://www.instagram.com/",
    fees: "Underground Mine: ¥1,800, Crystal River: ¥800, Crystal Geode Splitting Experience: ¥700",
    busCourses: ["A", "C", "D", "E", "F"],
  },
  5: {
    id: 5,
    description: "Bus stop location for the Kyubii bus routes.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: ["A", "D", "E", "F"],
  },
  6: {
    id: 6,
    description: "This spot lets you enjoy the expressions and stories of bears arranged by era and theme. The museum features a warm, inviting space enveloped in the comfort of wood, showcasing a diverse collection ranging from antique bears to artist creations. With an array of adorable goods available, it's a museum recommended for families and couples alike.",
    address: "1185-4 Takaku Hei, Nasu Town 325-0302",
    phone: null,
    businessHours: "Opening Hours: 9:30 AM - 5:00 PM, Closed: Second Tuesday of February, March, June, and December",
    website: "https://www.teddynet.co.jp/nasu/",
    fees: "Adults: ¥1,500, Middle/High School Students: ¥1,000, Elementary School Students: ¥800",
    busCourses: ["A", "D", "E", "F"],
  },
  7: {
    id: 7,
    description: "This lakeside leisure facility, surrounded by the rich nature of Nasu, is a popular spot for families to enjoy. Visitors can interact with alpacas, goats, and cows, and also experience milking and feeding. Boating is available on the lake, and soft serve ice cream made with special milk is one of the signature treats.",
    address: "414-2 Takaku-he, Nasu Town 325-0397",
    phone: null,
    businessHours: "9:30 AM - 4:30 PM, Regular Holidays: Open year-round",
    website: "https://www.rindo.co.jp/",
    fees: "Adults: ¥1,600, Elementary School Students: ¥800, Senior Discount: ¥1,100, Disability Discount: ¥800",
    busCourses: ["A", "D", "E", "F"],
  },
  8: {
    id: 8,
    description: "This popular inn offers a relaxing stay experience. Its spacious guest rooms feature a soothing design with the warmth of wood, creating an inviting space to unwind. The cuisine showcases local ingredients through both buffet and course options, delivering a rich and satisfying dining experience.",
    address: "4449-2 Takaku Hei, Nasu Town 325-0302",
    phone: null,
    businessHours: "Check-in: 3:00 PM, Check-out: 11:00 AM, Hot Springs: 6:00 AM - 11:00 PM / 3:00 PM - 11:00 PM",
    website: "https://grand-mercure-nasuhighlands.com/",
    fees: "From ¥16,150 per person per night (breakfast included)",
    busCourses: ["A", "D", "E", "F"],
  },
  9: {
    id: 9,
    description: "The Nasu Stained Glass Museum is Japan's largest antique stained glass museum, an experience to be enjoyed with all five senses. Gentle light, the beautiful melody of the pipe organ, the soothing tones of the music box, majestic stone statues, elegant furnishings, and a calming fragrance... gifts from the angels.",
    address: "1790 Takaku-he, Nasu Town 325-0302",
    phone: null,
    businessHours: "Museum: 9:30 AM - 4:30 PM, Stained Glass Workshop: 9:30 AM - 3:30 PM, Closed: Wednesdays",
    website: "https://sgm-nasu.com/",
    fees: "Adults: ¥1,600, Middle/High School Students: ¥1,000, Elementary School Students: ¥500, Infants: Free",
    busCourses: ["A", "C", "D"],
  },
  10: {
    id: 10,
    description: "Currently suspended.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: [],
  },
  11: {
    id: 11,
    description: "Bus stop location for the Kyubii bus routes.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: ["A", "C", "D"],
  },
  12: {
    id: 12,
    description: "Relax to your heart's content in tranquil Japanese-style rooms enveloped by nature throughout the seasons. Meals feature vibrant kaiseki cuisine showcasing local ingredients. Warm hospitality and quality hot springs gently soothe daily fatigue, delivering leisurely moments at this charming inn.",
    address: "22 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "Check-in: 3:00 PM - 5:30 PM, Check-out: 10:00 AM, Hot Springs: Day-use bathing 10:30 AM - 2:00 PM",
    website: "https://nigoriyu-sankai.com/",
    fees: "Starting at ¥16,000 per person per night (includes dinner and breakfast)",
    busCourses: ["A", "D"],
  },
  13: {
    id: 13,
    description: "Hotel Sun Valley Nasu features a variety of accommodations, including elegant hotels for enjoying a luxurious resort experience, cozy lodgings nestled in the greenery of Nasu Highlands, and buildings with open-air baths where you can fully savor Nasu Onsen. You can savor delicious meals featuring menus that highlight seasonal local ingredients.",
    address: "203 Yumoto, Nasu Town 325-0392",
    phone: null,
    businessHours: "Check-in: 3:00 PM, Check-out: 10:00 AM, Hot Springs: 10:00 AM - 9:00 PM",
    website: "https://www.nasu3800.co.jp/",
    fees: "Starting at ¥10,000 per person per night (includes dinner and breakfast)",
    busCourses: ["A", "D"],
  },
  14: {
    id: 14,
    description: "Bus stop location for the Kyubii bus routes.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: ["A", "D"],
  },
  15: {
    id: 15,
    description: "Nestled within the forests of Nasu, this serene space greets visitors with quiet hospitality. The tree-lined approach transforms with each season, offering beautiful greenery, vibrant autumn foliage, and snowy landscapes. Soft lighting leading to the building hints at the warm welcome within.",
    address: "206 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "Check-in: 3:00 PM, Check-out: 10:30 AM, Hot Springs: 3:00 PM - 10:30 AM the following day",
    website: "https://sansuikaku.com/",
    fees: "From ¥42,100 per person per night (including dinner and breakfast)",
    busCourses: ["A", "D"],
  },
  16: {
    id: 16,
    description: "Nestled amidst the lush landscapes of Nasu, this simple, warm soba restaurant offers a serene space where you can savor aromatic handmade soba noodles. The clean, pure broth complements the noodles perfectly, creating a simple yet profoundly satisfying flavor.",
    address: "370-7 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "11:00 AM - 3:00 PM (Closes when soba runs out), Regular holiday: Tuesday",
    website: "https://www.instagram.com/nasuteuchisoba/",
    fees: "Mori Soba: ¥900 and up, Recommended Chilled Tempura Mori Soba: ¥2,000",
    busCourses: ["A", "C", "D"],
  },
  17: {
    id: 17,
    description: "The Fujishiro Seiji Museum of Art is a museum in Nasu Highlands where visitors can fully immerse themselves in the world of shadow artist Fujishiro Seiji. The museum displays numerous fantastical shadow artworks woven from light and shadow, captivating visitors with their vivid colors and intricate details. Exhibitions change seasonally.",
    address: "203 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "9:30 AM - 4:30 PM (Last admission at 4:00 PM), Closed: Tuesdays, Year-end and New Year holidays",
    website: "https://fujishiro-seiji-museum.jp/",
    fees: "General Admission: ¥2,000, Ages 70 and over: ¥1,900, Junior High School Students and younger: ¥1,300",
    busCourses: ["A", "C", "D"],
  },
  18: {
    id: 18,
    description: "Minamigaoka Farm is a free-admission tourist farm in Nasu Town specializing in dairy farming. It raises rare Guernsey cows, and its rich, sweet milk and soft-serve ice cream are famous. Visitors can enjoy diverse experiences such as interacting with animals, butter and ice cream making workshops, and fishing ponds.",
    address: "579 Yumoto, Nasu Town 325-0393",
    phone: null,
    businessHours: "8:00 AM - 5:30 PM (Subject to change depending on season, weather, etc.), Ice Cream Making Experience: 1:40 PM - 2:10 PM",
    website: "https://www.minamigaoka.co.jp/",
    fees: "Admission and parking are free, Ice cream making experience: From ¥1,700",
    busCourses: ["A", "C", "D"],
  },
  19: {
    id: 19,
    description: "This cottage-style resort features spacious accommodations designed to prioritize privacy. Some cottages include private hot springs, making them perfect for family vacations or group trips. The grounds offer a variety of activities and partner facilities, with convenient access to Nasu Highland Park.",
    address: "3375 Takaku-otsu, Nasu Town 325-0303",
    phone: null,
    businessHours: "Check-in: 4:00 PM, Check-out: 10:00 AM, Hot Springs: 1:00 PM - 11:00 PM",
    website: "https://www.pure-cottages.jp/",
    fees: "Starting at ¥16,500 per person per night (includes dinner and breakfast)",
    busCourses: ["A", "D"],
  },
  20: {
    id: 20,
    description: "Nestled in the great outdoors of Nasu Highlands, this is one of the largest amusement parks in northern Kanto, offering everything from thrill rides to kid-friendly attractions. With a pet-friendly area, it's a classic Nasu leisure spot where you can enjoy nature and fun together.",
    address: "3375 Takaku-otsu, Nasu Town 325-0398",
    phone: null,
    businessHours: "9:30 AM - 4:30 PM, Regular Holidays: Open year-round",
    website: "https://www.nasuhai.co.jp/",
    fees: "Adult: ¥1,600, Child: ¥800, Senior: ¥800, Disability Discount: ¥800, Dog: ¥500",
    busCourses: ["A", "D"],
  },
  21: {
    id: 21,
    description: "This popular lodging spot is ideal for families and group trips. The spacious cottages offer the freedom to cook your own meals or enjoy barbecues. Surrounded by trees, the quiet environment provides a sense of privacy, and pet-friendly options are available. With many nearby attractions, it's perfect for those seeking a relaxing getaway in nature.",
    address: "2332 Takaku-otsu, Nasu Town 325-0303",
    phone: null,
    businessHours: "Check-in: 3:00 PM, Check-out: 10:00 AM, Hot Springs: 12:00 PM - 9:00 PM",
    website: "https://www.nasuvillage.com/contents03.html",
    fees: "1 night for 3 guests: From ¥15,600, Breakfast: ¥1,800",
    busCourses: ["A", "D"],
  },
  22: {
    id: 22,
    description: "In the village of clear streams, underground water from the Nasu Mountains flows as waterfalls, where you can fish for char and rainbow trout. You can savor river fish with no distinctive odor. Our 'Tochigi Shamo Tsukesoba,' certified as a Nasu Brand product, is a signature dish we take pride in. Please give it a try!",
    address: "2714-2 Takaku-otsu, Nasu Town 325-0303",
    phone: null,
    businessHours: "Fishing Pond: 9:00 AM - 4:00 PM, Meals: 11:00 AM - 4:00 PM, Regular Holidays: Thursdays and New Year's Day",
    website: "https://www.seiryunosato.com/",
    fees: "Rod rental: ¥200 per rod, Grilling fee: ¥250 per fish",
    busCourses: ["A", "C", "D"],
  },
  23: {
    id: 23,
    description: "Nasu Safari Park is home to approximately 500 animals representing 50 species from around the world, including lions, tigers, giraffes, hippos, and elephants. You can experience feeding herbivores like giraffes and elephants, and witness the power of carnivores up close.",
    address: "3523 Takaku-otsu, Nasu Town 325-0303",
    phone: null,
    businessHours: "Weekdays: 9:30 AM - 5:00 PM, Saturdays, Sundays, and Holidays: 9:00 AM - 5:00 PM, Closed: Thursdays",
    website: "https://www.nasusafari.com/",
    fees: "Adults (Middle school and above): ¥3,200, Children (Ages 3–Elementary school): ¥1,900",
    busCourses: ["A", "C"],
  },
  24: {
    id: 24,
    description: "Bus stop location for the Kyubii bus routes.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: ["A", "C", "D"],
  },
  25: {
    id: 25,
    description: "Candle House Shushu is a popular candle specialty shop in Nasu Highlands, offering a relaxing spot where you can enjoy handmade candle experiences. The shop features a wide variety of candles, with seasonal and themed pieces delighting the eye. At the workshop, you can create your very own candle.",
    address: "796-234 Takaku, Nasu Town 325-0303",
    phone: null,
    businessHours: "10:00 AM - 6:00 PM, Regular Closing Day: Thursday",
    website: "https://chouchoustyle.com/",
    fees: "Candle Making: ¥880~, Sparkling Aroma Candle: ¥1650~",
    busCourses: ["A", "C", "D"],
  },
  26: {
    id: 26,
    description: "Stream Park is an outdoor leisure spot nestled along a mountain stream surrounded by rich nature. In the area where clear water flows, visitors can enjoy catching fish with their hands or fishing experiences, and the charm lies in relaxing while listening to the gentle murmur of the river.",
    address: "213 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "9:00 AM - 4:00 PM, Regular Holiday: Thursday (Open year-round)",
    website: "https://www.e-nkp.com/",
    fees: "Rod rental: ¥200 per rod, Go-kart (single-rider): ¥1,000",
    busCourses: ["C"],
  },
  27: {
    id: 27,
    description: "This popular bakery and restaurant in Nasu Highlands charms visitors with its picture-book atmosphere nestled in the forest. The aroma of freshly baked bread fills the air inside, where a diverse array of breads—including the famous blueberry bread—is displayed in abundance. It's also renowned as a photogenic spot.",
    address: "656-2 Yumoto, Nasu Town 325-0301",
    phone: null,
    businessHours: "8:00 AM - 6:00 PM, Morning: 8:00 AM - 10:00 AM, Lunch: 10:00 AM - 5:00 PM",
    website: "https://pennylane.company/",
    fees: "Per person: ¥1,000 to ¥2,000",
    busCourses: ["C"],
  },
  28: {
    id: 28,
    description: "The park is home to many species of monkeys, from small to large, and visitors can observe them moving energetically in an environment close to nature. The feeding experience is also well-developed, allowing you to thoroughly enjoy the monkeys' expressions and gestures. It's a spot that brings smiles to the faces of children alike.",
    address: "6146 Takaku-ko, Nasu Town 325-0001",
    phone: null,
    businessHours: "Weekdays: 9:30 AM - 4:00 PM, Saturdays, Sundays, and Holidays: 9:30 AM - 4:30 PM, Regular Holidays: Wednesdays and Thursdays",
    website: "https://www.nasumonkey.com/",
    fees: "Adults: ¥2,300, Children (ages 3–elementary school): ¥1,200, Group discounts available (15 or more people)",
    busCourses: ["E"],
  },
  29: {
    id: 29,
    description: "This interactive museum lets you enjoy a mysterious world created using optical illusions. Inside, three distinct galleries are packed with interactive exhibits you can touch, play with, and photograph. It's a popular spot where you can take pictures that look like you've stepped into a painting—perfect for rainy days.",
    address: "5760 Takaku-ko, Nasu Town 325-0304",
    phone: null,
    businessHours: "Trick Art Museum: 9:00 AM - 5:00 PM, Trick Art Maze? Museum: 9:00 AM - 5:00 PM, Michelangelo Museum: 9:00 AM - 5:00 PM",
    website: "https://www.trick-art.jp/",
    fees: "Adults: ¥1,300, Ages 4–Junior High School: ¥800, Ages 3 and under: Free",
    busCourses: ["E"],
  },
  30: {
    id: 30,
    description: "GOOD NEWS is a new lifestyle complex born in Nasu Highlands, offering a delightful space themed around 'Food, Travel, and the Future.' Surrounded by greenery, the grounds feature unique shops like local ingredient stores and cafes, creating an exciting atmosphere just by walking through.",
    address: "24-1 Takaku-o, Nasu Town 325-0303",
    phone: null,
    businessHours: "9:00 AM - 5:00 PM, Regular Holiday: Second Thursday of the month",
    website: "https://gooooodnews.com/",
    fees: "Parking: ¥500 per vehicle",
    busCourses: ["E"],
  },
  31: {
    id: 31,
    description: "A charming sweets shop known for its delightful confections and treats. The building itself is designed like a castle, creating a magical atmosphere. Visitors can enjoy a variety of sweets including cakes, cookies, and traditional Japanese confections while exploring the whimsical interior.",
    address: "4588-10 Takaku-ko, Nasu Town 325-0001",
    phone: null,
    businessHours: "Weekdays: 9:00 AM - 5:30 PM, Saturdays, Sundays, and Holidays: 9:00 AM - 6:00 PM, Regular Holidays: Open year-round",
    website: "https://www.okashinoshiro.co.jp/",
    fees: "Free admission, Coffee/Tea: ¥300",
    busCourses: ["E"],
  },
  32: {
    id: 32,
    description: "Entrance point for the Loisir Hotel Nasu, a comfortable accommodation option in the Nasu Highlands area offering modern amenities and easy access to local attractions.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: ["C"],
  },
  33: {
    id: 33,
    description: "Bus stop location for the Kyubii bus routes.",
    address: null,
    phone: null,
    businessHours: null,
    website: null,
    fees: null,
    busCourses: [],
  },
};

// Helper function to get details for a spot
export function getSpotDetails(id: number): SpotDetails | undefined {
  return spotDetails[id];
}
